//! Witness generation for auipc component.

use num_traits::Zero;
use stwo::core::ColumnVec;
use stwo::core::fields::m31::BaseField;
use stwo::core::fields::qm31::QM31;
use stwo::prover::backend::simd::SimdBackend;
use stwo::prover::poly::BitReversedOrder;
use stwo::prover::poly::circle::CircleEvaluation;

use runner::trace::prover_columns::AuipcColumns;

/// Generate interaction trace for LogUp.
///
/// The fraction columns are generated by the `auipc_interaction!` macro
/// from the table's `lookups:` block — the same declaration the AIR
/// consumes, so entry order and pairing match by construction.
pub fn gen_interaction_trace(
    trace: &[CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>],
    relations: &crate::relations::Relations,
) -> (
    ColumnVec<CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>>,
    QM31,
) {
    if trace.is_empty() {
        return (vec![], QM31::zero());
    }
    runner::auipc_interaction!(trace, relations)
}

/// Register multiplicities for preprocessed lookups, from the same
/// `lookups:` declaration (the `preprocessed`-marked entries).
pub fn register_multiplicities(
    trace: &[CircleEvaluation<SimdBackend, BaseField, BitReversedOrder>],
    counters: &mut crate::relations::Counters,
) {
    if trace.is_empty() {
        return;
    }
    runner::auipc_register_multiplicities!(trace, counters);
}
