//! End-to-end tests comparing interpreter output with native execution.
//!
//! These tests automatically discover all examples from guest-lib and:
//! 1. Build guest ELF binaries (once per test run)
//! 2. Run them through the interpreter
//! 3. Compare the raw postcard bytes with native execution
//! 4. Optionally generate a STARK proof
//!
//! To add a new test, simply create a new module in guest/guest-lib/src/programs/
//! with a `test_call()` function that returns a serializable result.

use guest_lib::get_test_bytes;
use prover::e2e::run_guest_raw;
use prover::prove_rv32im;
use runner::run;
use stwo::core::fri::FriConfig;
use stwo::core::pcs::PcsConfig;

/// Test a single example by comparing guest output bytes with native output bytes.
fn test_example(name: &str) {
    let guest_bytes = run_guest_raw(name);
    let native_bytes = get_test_bytes(name).unwrap_or_else(|| panic!("Unknown example: {name}"));

    assert_eq!(
        guest_bytes, native_bytes,
        "Output mismatch for example '{name}'\n  Guest bytes: {guest_bytes:?}\n  Native bytes: {native_bytes:?}",
    );
}

// Individual test functions are auto-generated by build.rs
include!(concat!(env!("OUT_DIR"), "/e2e_tests.rs"));

/// PCS config for testing.
fn test_pcs_config() -> PcsConfig {
    PcsConfig {
        pow_bits: 10,
        fri_config: FriConfig::new(5, 1, 64),
    }
}

/// Test proving a small example (scaffolding - no real constraints yet).
#[test]
#[ignore = "Proving is slow, run with --ignored"]
fn test_prove_fibonacci() {
    use prover::e2e::{ensure_guest_built, guest_bin_dir};

    ensure_guest_built();

    let elf_path = guest_bin_dir().join("fib");
    let elf_bytes = std::fs::read(&elf_path).expect("Failed to read fib ELF");

    let run_result = run(&elf_bytes, 10_000_000).expect("Failed to run fib");

    // Generate proof
    let _proof = prove_rv32im(run_result, test_pcs_config());
}
