//! Guest library for zkVM programs.
//!
//! This library provides:
//! - Result types for guest-host communication
//! - The `guest_main!` macro for minimal boilerplate
//! - Program computations for testing
//! - I/O memory layout constants (`io` module)
//! - Optional heap allocation via bump allocator (`alloc` feature)

#![cfg_attr(target_arch = "riscv32", no_std)]
#![cfg_attr(
    all(target_arch = "riscv32", feature = "alloc"),
    feature(alloc_error_handler)
)]

// =============================================================================
// Modules
// =============================================================================

#[cfg(target_arch = "riscv32")]
pub mod io;
pub mod programs;

// Allocator module (riscv32 only, with alloc feature)
#[cfg(all(target_arch = "riscv32", feature = "alloc"))]
pub mod allocator;

#[cfg(target_arch = "riscv32")]
mod critical_section_impl;

// =============================================================================
// Re-exports
// =============================================================================

pub use programs::{
    BranchResult, ConstantResult, EcdsaResult, FactorialResult, FibResult, KeccakResult,
    LoadMergeResult, MemoryTestResult, MulDivResult, Sha2Result, branch, constant, ecdsa_verify,
    fact, fib, keccak256, load_merge, memory, muldiv, sha256,
};
#[cfg(feature = "revm")]
pub use programs::{RevmSmokeResult, revm_smoke};

// =============================================================================
// Test dispatcher (native only, auto-generated by build.rs)
// =============================================================================

#[cfg(not(target_arch = "riscv32"))]
include!(concat!(env!("OUT_DIR"), "/dispatcher.rs"));
