//! Guest library for zkVM programs.
//!
//! This library provides:
//! - Result types for guest-host communication
//! - The `guest_main!` macro for minimal boilerplate
//! - Program computations for testing

#![cfg_attr(target_arch = "riscv32", no_std)]

// =============================================================================
// Modules
// =============================================================================

pub mod programs;

// =============================================================================
// Re-exports
// =============================================================================

pub use programs::{
    BranchResult, ConstantResult, FactorialResult, FibResult, LoadMergeResult, MemoryTestResult,
    MulDivResult, branch, constant, fact, fib, load_merge, memory, muldiv,
};

// =============================================================================
// Test dispatcher (native only, auto-generated by build.rs)
// =============================================================================

#[cfg(not(target_arch = "riscv32"))]
include!(concat!(env!("OUT_DIR"), "/dispatcher.rs"));
